### PR TITLE
upgrade to Pants 2.0.0.dev9

### PR DESCRIPTION
**Pull request by tdyas**

### CODE REVIEW

**Comment by tdyas** [comment]
@Eric-Arellano: Build is failing with `Exception: Unmatched glob from file arguments: "helloworld/main_pb2.py"`. Is that from a change in dev9?

**Comment by Eric-Arellano** [comment]
Oof. Apparently I merged dev8 on red. My bad. In `.travis.yml`, chang `_pb2.py` to `_py2.py`. Typo in the file arg.

**Comment by asherf** [comment]
Screen Shot 2020-08-20 at 8 14 28 AM

**Comment by benjyw** [comment]
Note: typo and py2 constraint issues fixed in https://github.com/pantsbuild/example-python/pull/39

**Comment by tdyas** [comment]
Latest build failure:

```
pex.vendor._vendored.setuptools.pkg_resources.ContextualVersionConflict: (importlib-resources 3.0.0 (/home/vagrant/.pex/installed_wheels/356a69e89b60e58a9f454fae2aa19f4e0501c768/importlib_resources-3.0.0-py2.py3-none-any.whl), Requirement.parse('importlib-resources<2,>=1.0; python_version < "3.7"'), set(['virtualenv']))
```

I only understand that this exception is probably something wrong with constraints. It tells me nothing about how to resolve it though.

**Comment by Eric-Arellano** [comment]
Thanks!

**Pull request merged**
