### PR TITLE
Bump to 1.29.0

### PR DESCRIPTION
**Pull request by stuhood**

### CODE REVIEW

**Comment by stuhood** [comment]
Will be updated to `1.29.0` after release.

**Comment by stuhood** [comment]
Whoops. Forgot #20 was out.

**Comment by Eric-Arellano** [comment]
I forgot #20 was out too, hehe. Merged. But it targets an rc, so will probably want to revive this PR when 1.29.0 is out.

**Comment by stuhood** [comment]
@Eric-Arellano : Thanks! In future, we might want to treat the example repo as similar to the docsite... ie avoid landing things there until they're stable? But maybe rcs are "stable enough"...

**Comment by Eric-Arellano** [comment]
Fair. As explained elsewhere, I think also that v2 Python is becoming stable/polished enough that we no longer need to upgrade this as aggressively.

**Pull request closed without merging**
