### PR TITLE
ci: upgrade action version

### PR DESCRIPTION
**Pull request by rhuanbarreto**
Also remove some line breaks for better legibility

### CODE REVIEW

**Review by benjyw — APPROVED** [review]

**Comment by rhuanbarreto** [comment]
@benjyw how do I run CI for the PR?

**Comment by benjyw** [comment]
> @benjyw how do I run CI for the PR?

It should run automatically. Not sure what's going on. I'll take a peek.

**Comment by rhuanbarreto** [comment]
Maybe this? https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by benjyw** [comment]
I figure it's that, but I am an admin and I don't see the "Approve and run" button.

**Review by benjyw — APPROVED** [review]

**Comment by benjyw** [comment]
The only thing I can think of is that your change itself is preventing the job from running. Which is odd - even if you broke the yaml (which I don't think you did), we should see a job attempt that fails.

**Comment by benjyw** [comment]
@rhuanbarreto can you try removing your formatting changes and pushing, just to see if that moves anything along?

**Comment by rhuanbarreto** [comment]
@benjyw committed.

**Comment by benjyw** [comment]
Actually, some progress: https://github.com/pantsbuild/example-python/actions/runs/5597067338

**Comment by benjyw** [comment]
```[Invalid workflow file: .github/workflows/pants.yaml#L54](https://github.com/pantsbuild/example-python/actions/runs/5597067338/workflow)
You have an error in your yaml syntax on line 54```

**Comment by benjyw** [comment]
Basically you need to revert all your formatting changes, looks like. Just leave the v4->v5 upgrade.

**Comment by rhuanbarreto** [comment]
@benjyw done.

**Comment by kaos** [comment]
Ah yes, it's this syntax causes issues in yaml, need to be quoted:
```yaml
run: pants test ::

# vs

run: "pants test ::"
```

**Pull request merged**
