### PR TITLE
Upgrade to pants 2.12.0

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by asherf** [comment]
@Eric-Arellano

**Comment by asherf** [comment]
sorry, I don't have permissions to assign reviewers.

**Review by stuhood — APPROVED** [review]
Thanks!

**Comment by Eric-Arellano** [comment]
Thanks!

For future reference, @stuhood gentle remember we need to create a `2.11` branch too. I've pushed that.

**Pull request merged**
