### PR TITLE
Fix the setup-py part of the example.

### PR DESCRIPTION
**Pull request by benjyw**
Required moving the .proto files to be
below the exported target (in the filesystem
sense).

If we support setting a source root on
generated protos in the future, we can
modify this further to demo that.

### CODE REVIEW

**Comment by benjyw** [comment]
TBH I don't understand cherry-picking this, unless the plan is to rename 2.0 to master at some point?

**Comment by Eric-Arellano** [comment]
Yeah, we plan to rename 2.0 to master. Or perhaps I should have made a 1.30 branch.

The idea is that we want to still have an example for users not yet ready to upgrade to 2.0, given that it's still a dev release.

**Comment by benjyw** [comment]
Yeah, was going to cherrypick that separately, although if we're going to rename then I can just remove it in this commit.

**Comment by Eric-Arellano** [comment]
Either way is fine with me. I think I'd prefer keeping the `master` branch using 1.30 until we have at least the alpha release for 2.0, but not a huge deal so long as we have two branches.

**Comment by benjyw** [comment]
In fact that'll be nice because then after we rename the file won't even appear in the history.

**Comment by benjyw** [comment]
Pushed the commit here, so we can merge them together.

**Comment by benjyw** [comment]
I guess when we rename 2.0 we can first rename master to 1.30

**Comment by benjyw** [comment]
Going to merge since it's just a cherrypick, and it's not to master.

**Pull request merged**
