### PR TITLE
Update pytest & running tailor in CI

### PR DESCRIPTION
**Pull request by asherf**
see: https://github.com/pantsbuild/example-python/pull/109#issuecomment-1282640689

### CODE REVIEW

**Review by benjyw — APPROVED** [review]

**Comment by asherf** [comment]
Ping

**Comment by benjyw** [comment]
I approved this last week... :)

**Comment by asherf** [comment]
@benjyw I don't have permissions to merge this... hence the ping

**Comment by benjyw** [comment]
Ah, I missed that. Sorry. Merging.

**Pull request merged**
